//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NonBaoHiemRoyalHelmet
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.CTDHs = new HashSet<CTDH>();
        }
    
        public string MaDH { get; set; }
        public string MaKH { get; set; }
        public string MaQTV { get; set; }
        public System.DateTime NgayDH { get; set; }
        public System.DateTime NgayGH { get; set; }
        public string PTTT { get; set; }
        public string TrangThai { get; set; }
        public int TongTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDH> CTDHs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual QuanTriVien QuanTriVien { get; set; }
    }
}
